spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suwei?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#mybatis配置
mybatis:
  typeAliasesPackage: com.example.authority.modules.**.entity
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:/mybatis-config.xml